---
- name: Convertir VM seed a Template
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vault.yml

  tasks:
    - name: Asegurar VM seed apagada
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ seed_vm_name }}"
        state: poweredoff
        state_change_timeout: 600

    # Opción A: crear Template en carpeta local de vCenter (fácil y directa)
    - name: Crear template en carpeta de vCenter desde VM
      vmware.vmware.folder_template_from_vm:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        vm_name: "{{ seed_vm_name }}"
        template_name: "{{ template_name }}"
      register: template_result