---
- name: Instalar Docker en todos
  hosts: infra
  become: true
  roles:
    - role: docker

- name: Portainer Server en infra-master
  hosts: infra_master
  become: true
  roles:
    - role: portainer_server

- name: Portainer Agent en nodos
  hosts: infra_nodos
  become: true
  roles:
    - role: portainer_agent