---
# === ISO (defaults) ===
ubuntu_iso_url: ""
ubuntu_iso_local: ""
datastore_iso_dir: "iso"
existing_datastore_iso: ""

# === Nombres (defaults) ===
seed_vm_name: "ubuntu-seed-24-04"
template_name: "ubuntu-24-04-template"