---
# Defaults del rol (robusto aunque falten group_vars)
ubuntu_iso_url: ""
ubuntu_iso_local: ""
datastore_iso_dir: "iso"
# Si el ISO ya existe en el datastore, define aqu√≠ la ruta completa [DATASTORE] carpeta/archivo.iso
existing_datastore_iso: ""