version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: itop-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: S0p0rt3..
      MYSQL_DATABASE: itop
      MYSQL_USER: itop
      MYSQL_PASSWORD: S0p0rt3..
    volumes:
      - itop_db_data:/var/lib/mysql
    networks:
      - itop_net

  itop:
    image: vbkunin/itop:3.2.2   # iTop > 3.11
    container_name: itop-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"               # Acceso desde tu PC: http://192.168.5.85:8080
    environment:
      # Variables que espera el config-itop.php de esta imagen
      DB_HOSTNAME: db
      DB_ENV_MYSQL_DATABASE: itop
      DB_ENV_MYSQL_USER: itop
      DB_ENV_MYSQL_PASSWORD: S0p0rt3..
      DB_PREFIX: itop_
      PHP_TIMEZONE: America/Costa_Rica
    networks:
      - itop_net

networks:
  itop_net:
    driver: bridge

volumes:
  itop_db_data: