version: "3.8"

services:
  itop:
    image: vbkunin/itop:2.7.0-beta
    container_name: itop
    restart: always
    ports:
      - "8080:80"        
    volumes:
      - itop_extensions:/var/www/html/extensions
    networks:
      - itop-net

networks:
  itop-net:
    driver: bridge

volumes:
  itop_extensions: