---
# =========================
# Defaults del rol (seguros)
# =========================

# --- vCenter (backups para evitar 'undefined') ---
vcenter_hostname: ""
vcenter_datacenter: ""
vcenter_cluster: ""
vcenter_datastore: ""
vcenter_network: ""
vcenter_validate_certs: false
vcenter_username: "{{ vault_vcenter_username | default('') }}"
vcenter_password: "{{ vault_vcenter_password | default('') }}"
vm_folder: "Infra"

# --- ISO / Datastore ---
ubuntu_iso_url: ""                # p.ej.: "https://releases.ubuntu.com/24.04/ubuntu-24.04.3-live-server-amd64.iso"
ubuntu_iso_local: ""              # p.ej.: "/home/ansible/isos/ubuntu-24.04.3-live-server-amd64.iso"
datastore_iso_dir: "iso"          # subcarpeta destino en el datastore si hay que subir
existing_datastore_iso: ""        # p.ej.: "[DATASTORE] ISOS/ubuntu-24.04.3-live-server-amd64.iso"

# --- Nombres de recursos ---
seed_vm_name: "ubuntu-seed-24-04"
template_name: "ubuntu-24-04-template"

# --- Usuario Linux inicial (para cloud-init) ---
linux_user: "ubuntu"
disable_password_ssh: true

# --- SSH (solo keys) ---
ssh_pubkey_path: "~/.ssh/id_ed25519.pub"
auto_create_ssh_key: true
ssh_key_type: "ed25519"           # usa 'rsa' si lo prefieres
ssh_key_bits: 4096                # sólo si ssh_key_type = 'rsa'

# --- Red (defaults mínimos) ---
net_interface: "ens160"
guest_netmask: "255.255.255.0"
guest_gateway: "192.168.5.252"
guest_dns_servers:
  - "8.8.8.8"
guest_domain: "localdomain"

# --- Hardware por defecto de la seed ---
vm_cpu: 3
vm_ram_mb: 32768
vm_disk_gb: 120