$ANSIBLE_VAULT;1.1;AES256
62326164636139663263343639363331353265316435323165383232653564393261363636326639
3834623938376536386564643635336463623239646264620a326633326563613739353937346161
66326365646236616531393061653165393766656235373338333331643132633230333230353863
3561663931366134370a663438636561326233373133366661303238376531386135366432303535
33366464303835373661613338373161656638336436376530366636376461393561663934646631
39363731306463393735643333663330663334383437626339383735633833626535396263313436
61393436653339663565393334623138383166356466393832336136653538306337326235666666
65636430383564343531393764303933386561306430356531643539656435623261373161303131
31663238363634353966336462386639346361323662666461316636636135636536393561336563
61306138303766393133306237363032633932333062323237363562636264646161316435353666
37353762323635653032613062376333663436343932653930303432613533383437613832663534
39363639656339373738386164373461323465366265393839316135306435343630633664646437
36623363663435643164376635363836346362373334306663373733616232643036
