$ANSIBLE_VAULT;1.1;AES256
61626436333535376265646430633938303933373037656362656166336533626537653637323334
6361363336626265333339326534393735353134356237380a396333343064376238306637643231
30333862653438623365376230653665393531656534623666656539376537316430623230623532
3432646332613334370a623237343731353139376330303665633634333064366133643133353563
36353034643261323739663762353238663738363930326132643832396666643564643934636464
34396463623939643965313861303964613030666633623731326331323261373437303834616533
37373864336132313762396132353737316439636232313166333737306132373461666662633864
31396536656339613966333831366562383330386462323565653537663738636461663835613131
64363035376239666264616130363636613461613530376630373930303363323131
