$ANSIBLE_VAULT;1.1;AES256
30353166333638306333633539343262633738636433666663303538623839633834356639343236
6232623039316337373638356238653539363031383062300a623539396362336238656362376139
61383666636232646333643030313366306361323564336630376432376632323139373033313434
6636393862393764370a343233373265613262663536613463353434383930666236356662303264
38643031306366643433353935383961303163613664373033363133626638666439316538326330
35653837663338386462393764656632336138616333353037313666366536343032333439643631
63316532353430626666353638366334386663333461636463323432336231313333623031623836
32613139323632656265333965386231336134396530616664356333306337373632626463326262
61643939613436333532356336313532363166356337333639323738396262373830
