$ANSIBLE_VAULT;1.1;AES256
38313562346334316237386530636561633165316333393231653364623737636462653633303335
3031333164383531663339343333393332616632323738640a356362323633643066353963646637
31623262616564346136343837306461343731303939366164663164386531633830376166616534
3132313265666134620a636335373632343133396437366637633239316332643534313633643366
66633665633534393230386334353839376363643836313064663939373630633138643235613037
65663930346264343332613466323633393734303231386666643435363036643564636261333131
63653861643864333962643435626566613232386463616430333639366439373661663632623539
35636663653765623234646339663337346432376365343032646665326137353432663335346539
66303835376661303365336331356335653137666433363266636361653039323839323238343262
31343161313232613930636533313366643737613530363539653435303166653632383966623762
31656363613631376662663364633762653530303635313562333136316436653662396536323237
63363065643830376462396565646430356238343339663861303731373134666237363039616664
36646138633961393835363666646430353831643334323430366565343734626165
