$ANSIBLE_VAULT;1.1;AES256
66336635376537343139326336613432656235333232626362303363666563396161396162383566
6365353133613939323864613230386166353535653861380a356564313633326138356238376563
63646639333536363838636433353034323966666162373931663836316239326263633039386539
3263373762313437390a643965333330356364646636393266306464373134623630373537303230
65353538386362663061613037313961333061653765376534366339616336356631633334616230
34303732363666393566633430623830643238376635386436396234323838633565343133353265
38353166373164663233393530386135366539636665383863643535656239636232333862366161
30373165643533313362613731616563343135346438636561616334316238613138626539366633
32666638366631316634613938626339383335336365333036336130643139363537333233343030
37353166616438663432613237613964343462633466313036353237636664383434663132643136
31623362633731383961626136313165633233396238626534306530303739303735643563656563
32653037643830373939333338363734643234323733323765613033393131643437333736313230
63306262343165653633643638316335363437663265666663303434646233336332356130373231
34386239346265613765303637613562383430356466373934653361363461313133383866373930
366536636633306237336436303739323732
