---
- name: Test conexi贸n a vCenter desde localhost
  hosts: localhost
  gather_facts: false
  become: false         # <- IMPORTANTE: NO usar sudo

  collections:
    - community.vmware

  tasks:
    - name: Obtener informaci贸n de vCenter (versi贸n)
      vmware_about_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vcenter_info

    - name: Mostrar informaci贸n del vCenter
      debug:
        var: vcenter_info