$ANSIBLE_VAULT;1.1;AES256
63656636316362343939396332393338306365373862643664373766363566663834323834616537
6333356634333535373038396538386232663837663861310a643631313166366465363437343039
65373537653032323266633361663832666532653136613531353139306537336134313234643562
3238336531323865320a303435376235643563336634616164626462376535356631303031663765
33346661396534303361623037616234636431316335343236353337623832333634316165333932
37376132326561353334396432323038386161623964326463373138373964353334346237363761
66326565313964663035343633376262376134366132633537376530376664663962316666363932
34653239333130623563363537363962333831386333653732393764613834303637643664643063
3636
