$ANSIBLE_VAULT;1.1;AES256
62646332643636383466666138323537343664303339373534653934373932396139363766383139
3061633737663637653439333765333430393662613765370a613461316237623531616263663466
36623232326361326431333965666666623837643839623831623165613964616331333164616438
3965656663383761330a363735636263393936323436663735363061353032323336316162306664
33346538313132383765633238396539353135656466313663663365396163643164613963616137
66613234643465333364303735306338656432653835353066623238613136343431313362393131
34616138343064313730613237666466323566383931363964383238323263363761396333623439
34663335336333376130373465396432353735383931346630316462376131343261353435333332
62616232326438386431663534326239373537333164626135353262343239643361356262346461
3235633037623163303937353764303133626361353966363164
