---
- name: Volumen de Portainer
  community.general.docker_volume:
    name: portainer_data
    state: present

- name: Portainer Server (CE)
  community.general.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"