---
- name: Esperar a que autoinstall termine en {{ seed_vm_name }}
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Usar Python del venv
      ansible.builtin.set_fact:
        ansible_python_interpreter: "/home/ansible/.ansible/venvs/vmware/bin/python"

  tasks:
    - name: Esperar hasta 3600s a que la VM tenga IP y Tools (autoinstall)
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ seed_vm_name }}"
      register: vm_info
      retries: 60
      delay: 60
      until: >
        (vm_info.instance.guest_tools_status is defined and vm_info.instance.guest_tools_status in ['guestToolsRunning', 'guestToolsExecutingScripts']) and
        (vm_info.instance.ipv4 is defined and vm_info.instance.ipv4 | length > 0)
      failed_when: false

    - name: Mostrar resultado final de la espera
      ansible.builtin.debug:
        msg:
          power_state: "{{ (vm_info.instance.hw_power_status | default('unknown')) }}"
          tools_status: "{{ (vm_info.instance.guest_tools_status | default('unknown')) }}"
          ipv4: "{{ (vm_info.instance.ipv4 | default('')) }}"